#!/usr/bin/env bash
# usage: envchain mackerel ./bench

set -ex

ROOT=$(cd $(dirname $0);pwd)

echo "clear logs"
# https://serverfault.com/a/980572
ssh -t isu01 "sudo rm -rf /var/log/nginx/access.log"
ssh -t isu01 "sudo rm -rf /var/log/nginx/error.log"
ssh -t isu01 "sudo nginx -s reload"
ssh -t isu01 "sudo truncate --size 0 /var/log/mysql/mysql-slow.log"

echo "start benchmark"
ssh -t bench "export MACKEREL_APIKEY=$MACKEREL_APIKEY; cd /home/isucon/isuumo/bench; echo \"score.mizdra \$(./bench --target-url http://18.183.153.63 | jq '.score') \$(date +%s)\" | mkr throw --service isucon10-qualify"

echo "fetch logs"
rsync -a --rsync-path="sudo rsync" isu01:/var/log/nginx/access.log $ROOT/log/access.log
rsync -a --rsync-path="sudo rsync" isu01:/var/log/nginx/error.log $ROOT/log/error.log
rsync -a --rsync-path="sudo rsync" isu01:/var/log/mysql/mysql-slow.log $ROOT/log/mysql-slow.log
